CREATE TABLE game(
   appid            INTEGER  NOT NULL PRIMARY KEY 
  ,name             VARCHAR(106) NOT NULL
  ,release_date     DATE  NOT NULL
  ,english          BIT  NOT NULL
  ,developer        VARCHAR(239) NOT NULL
  ,publisher        VARCHAR(129)
  ,platforms        VARCHAR(17) NOT NULL
  ,required_age     INTEGER  NOT NULL
  ,categories       VARCHAR(299) NOT NULL
  ,genres           VARCHAR(210) NOT NULL
  ,steamspy_tags    VARCHAR(59) NOT NULL
  ,achievements     INTEGER  NOT NULL
  ,positive_ratings INTEGER  NOT NULL
  ,negative_ratings INTEGER  NOT NULL
  ,average_playtime INTEGER  NOT NULL
  ,median_playtime  INTEGER  NOT NULL
  ,owners           VARCHAR(19) NOT NULL
  ,price            NUMERIC(6,2) NOT NULL
);

CREATE TABLE game_reqs(
   steam_appid        INTEGER  NOT NULL
  ,pc_requirements    VARCHAR(4260) NOT NULL
  ,mac_requirements   VARCHAR(2207) NOT NULL
  ,linux_requirements VARCHAR(2373) NOT NULL
  ,minimum            VARCHAR(2662)
  ,recommended        VARCHAR(2603)
);

CREATE TABLE game_support(
   steam_appid   INTEGER  NOT NULL
  ,website       VARCHAR(183)
  ,support_url   VARCHAR(349)
  ,support_email VARCHAR(247)
);

CREATE TABLE game_tags(
   appid                             INTEGER  NOT NULL
  ,`1980s`                             INTEGER  NOT NULL
  ,`1990s`                             INTEGER  NOT NULL
  ,`25d`                               INTEGER  NOT NULL
  ,`2d`                                INTEGER  NOT NULL
  ,`2d_fighter`                        INTEGER  NOT NULL
  ,`360_video`                         INTEGER  NOT NULL
  ,`3d`                                INTEGER  NOT NULL
  ,`3d_platformer`                     INTEGER  NOT NULL
  ,`3d_vision`                         INTEGER  NOT NULL
  ,`4_player_local`                    INTEGER  NOT NULL
  ,`4x`                                INTEGER  NOT NULL
  ,`6dof`                              INTEGER  NOT NULL
  ,atv                               INTEGER  NOT NULL
  ,abstract                          INTEGER  NOT NULL
  ,action                            INTEGER  NOT NULL
  ,action_rpg                        INTEGER  NOT NULL
  ,action_adventure                  INTEGER  NOT NULL
  ,addictive                         INTEGER  NOT NULL
  ,adventure                         INTEGER  NOT NULL
  ,agriculture                       INTEGER  NOT NULL
  ,aliens                            INTEGER  NOT NULL
  ,alternate_history                 INTEGER  NOT NULL
  ,america                           INTEGER  NOT NULL
  ,animation_modeling                INTEGER  NOT NULL
  ,anime                             INTEGER  NOT NULL
  ,arcade                            INTEGER  NOT NULL
  ,arena_shooter                     INTEGER  NOT NULL
  ,artificial_intelligence           INTEGER  NOT NULL
  ,assassin                          INTEGER  NOT NULL
  ,asynchronous_multiplayer          INTEGER  NOT NULL
  ,atmospheric                       INTEGER  NOT NULL
  ,audio_production                  INTEGER  NOT NULL
  ,bmx                               INTEGER  NOT NULL
  ,base_building                     INTEGER  NOT NULL
  ,baseball                          INTEGER  NOT NULL
  ,based_on_a_novel                  INTEGER  NOT NULL
  ,basketball                        INTEGER  NOT NULL
  ,batman                            INTEGER  NOT NULL
  ,battle_royale                     INTEGER  NOT NULL
  ,beat_em_up                        INTEGER  NOT NULL
  ,beautiful                         INTEGER  NOT NULL
  ,benchmark                         INTEGER  NOT NULL
  ,bikes                             INTEGER  NOT NULL
  ,blood                             INTEGER  NOT NULL
  ,board_game                        INTEGER  NOT NULL
  ,bowling                           INTEGER  NOT NULL
  ,building                          INTEGER  NOT NULL
  ,bullet_hell                       INTEGER  NOT NULL
  ,bullet_time                       INTEGER  NOT NULL
  ,crpg                              INTEGER  NOT NULL
  ,capitalism                        INTEGER  NOT NULL
  ,card_game                         INTEGER  NOT NULL
  ,cartoon                           INTEGER  NOT NULL
  ,cartoony                          INTEGER  NOT NULL
  ,casual                            INTEGER  NOT NULL
  ,cats                              INTEGER  NOT NULL
  ,character_action_game             INTEGER  NOT NULL
  ,character_customization           INTEGER  NOT NULL
  ,chess                             INTEGER  NOT NULL
  ,choices_matter                    INTEGER  NOT NULL
  ,choose_your_own_adventure         INTEGER  NOT NULL
  ,cinematic                         INTEGER  NOT NULL
  ,city_builder                      INTEGER  NOT NULL
  ,class_based                       INTEGER  NOT NULL
  ,classic                           INTEGER  NOT NULL
  ,clicker                           INTEGER  NOT NULL
  ,co_op                             INTEGER  NOT NULL
  ,co_op_campaign                    INTEGER  NOT NULL
  ,cold_war                          INTEGER  NOT NULL
  ,colorful                          INTEGER  NOT NULL
  ,comedy                            INTEGER  NOT NULL
  ,comic_book                        INTEGER  NOT NULL
  ,competitive                       INTEGER  NOT NULL
  ,conspiracy                        INTEGER  NOT NULL
  ,controller                        INTEGER  NOT NULL
  ,conversation                      INTEGER  NOT NULL
  ,crafting                          INTEGER  NOT NULL
  ,crime                             INTEGER  NOT NULL
  ,crowdfunded                       INTEGER  NOT NULL
  ,cult_classic                      INTEGER  NOT NULL
  ,cute                              INTEGER  NOT NULL
  ,cyberpunk                         INTEGER  NOT NULL
  ,cycling                           INTEGER  NOT NULL
  ,dark                              INTEGER  NOT NULL
  ,dark_comedy                       INTEGER  NOT NULL
  ,dark_fantasy                      INTEGER  NOT NULL
  ,dark_humor                        INTEGER  NOT NULL
  ,dating_sim                        INTEGER  NOT NULL
  ,demons                            INTEGER  NOT NULL
  ,design_illustration               INTEGER  NOT NULL
  ,destruction                       INTEGER  NOT NULL
  ,detective                         INTEGER  NOT NULL
  ,difficult                         INTEGER  NOT NULL
  ,dinosaurs                         INTEGER  NOT NULL
  ,diplomacy                         INTEGER  NOT NULL
  ,documentary                       INTEGER  NOT NULL
  ,dog                               INTEGER  NOT NULL
  ,dragons                           INTEGER  NOT NULL
  ,drama                             INTEGER  NOT NULL
  ,driving                           INTEGER  NOT NULL
  ,dungeon_crawler                   INTEGER  NOT NULL
  ,dungeons_dragons                  INTEGER  NOT NULL
  ,dynamic_narration                 INTEGER  NOT NULL
  ,dystopian_                        INTEGER  NOT NULL
  ,early_access                      INTEGER  NOT NULL
  ,economy                           INTEGER  NOT NULL
  ,education                         INTEGER  NOT NULL
  ,emotional                         INTEGER  NOT NULL
  ,epic                              INTEGER  NOT NULL
  ,episodic                          INTEGER  NOT NULL
  ,experience                        INTEGER  NOT NULL
  ,experimental                      INTEGER  NOT NULL
  ,exploration                       INTEGER  NOT NULL
  ,fmv                               INTEGER  NOT NULL
  ,fps                               INTEGER  NOT NULL
  ,faith                             INTEGER  NOT NULL
  ,family_friendly                   INTEGER  NOT NULL
  ,fantasy                           INTEGER  NOT NULL
  ,fast_paced                        INTEGER  NOT NULL
  ,feature_film                      INTEGER  NOT NULL
  ,female_protagonist                INTEGER  NOT NULL
  ,fighting                          INTEGER  NOT NULL
  ,first_person                      INTEGER  NOT NULL
  ,fishing                           INTEGER  NOT NULL
  ,flight                            INTEGER  NOT NULL
  ,football                          INTEGER  NOT NULL
  ,`foreign`                           INTEGER  NOT NULL
  ,free_to_play                      INTEGER  NOT NULL
  ,funny                             INTEGER  NOT NULL
  ,futuristic                        INTEGER  NOT NULL
  ,gambling                          INTEGER  NOT NULL
  ,game_development                  INTEGER  NOT NULL
  ,gamemaker                         INTEGER  NOT NULL
  ,games_workshop                    INTEGER  NOT NULL
  ,gaming                            INTEGER  NOT NULL
  ,god_game                          INTEGER  NOT NULL
  ,golf                              INTEGER  NOT NULL
  ,gore                              INTEGER  NOT NULL
  ,gothic                            INTEGER  NOT NULL
  ,grand_strategy                    INTEGER  NOT NULL
  ,great_soundtrack                  INTEGER  NOT NULL
  ,grid_based_movement               INTEGER  NOT NULL
  ,gun_customization                 INTEGER  NOT NULL
  ,hack_and_slash                    INTEGER  NOT NULL
  ,hacking                           INTEGER  NOT NULL
  ,hand_drawn                        INTEGER  NOT NULL
  ,hardware                          INTEGER  NOT NULL
  ,heist                             INTEGER  NOT NULL
  ,hex_grid                          INTEGER  NOT NULL
  ,hidden_object                     INTEGER  NOT NULL
  ,historical                        INTEGER  NOT NULL
  ,hockey                            INTEGER  NOT NULL
  ,horror                            INTEGER  NOT NULL
  ,horses                            INTEGER  NOT NULL
  ,hunting                           INTEGER  NOT NULL
  ,illuminati                        INTEGER  NOT NULL
  ,indie                             INTEGER  NOT NULL
  ,intentionally_awkward_controls    INTEGER  NOT NULL
  ,interactive_fiction               INTEGER  NOT NULL
  ,inventory_management              INTEGER  NOT NULL
  ,investigation                     INTEGER  NOT NULL
  ,isometric                         INTEGER  NOT NULL
  ,jrpg                              INTEGER  NOT NULL
  ,jet                               INTEGER  NOT NULL
  ,kickstarter                       INTEGER  NOT NULL
  ,lego                              INTEGER  NOT NULL
  ,lara_croft                        INTEGER  NOT NULL
  ,lemmings                          INTEGER  NOT NULL
  ,level_editor                      INTEGER  NOT NULL
  ,`linear`                            INTEGER  NOT NULL
  ,local_co_op                       INTEGER  NOT NULL
  ,local_multiplayer                 INTEGER  NOT NULL
  ,logic                             INTEGER  NOT NULL
  ,loot                              INTEGER  NOT NULL
  ,lore_rich                         INTEGER  NOT NULL
  ,lovecraftian                      INTEGER  NOT NULL
  ,mmorpg                            INTEGER  NOT NULL
  ,moba                              INTEGER  NOT NULL
  ,magic                             INTEGER  NOT NULL
  ,management                        INTEGER  NOT NULL
  ,mars                              INTEGER  NOT NULL
  ,martial_arts                      INTEGER  NOT NULL
  ,massively_multiplayer             INTEGER  NOT NULL
  ,masterpiece                       INTEGER  NOT NULL
  ,match_3                           INTEGER  NOT NULL
  ,mature                            INTEGER  NOT NULL
  ,mechs                             INTEGER  NOT NULL
  ,medieval                          INTEGER  NOT NULL
  ,memes                             INTEGER  NOT NULL
  ,metroidvania                      INTEGER  NOT NULL
  ,military                          INTEGER  NOT NULL
  ,mini_golf                         INTEGER  NOT NULL
  ,minigames                         INTEGER  NOT NULL
  ,minimalist                        INTEGER  NOT NULL
  ,mining                            INTEGER  NOT NULL
  ,`mod`                               INTEGER  NOT NULL
  ,moddable                          INTEGER  NOT NULL
  ,modern                            INTEGER  NOT NULL
  ,motocross                         INTEGER  NOT NULL
  ,motorbike                         INTEGER  NOT NULL
  ,mouse_only                        INTEGER  NOT NULL
  ,movie                             INTEGER  NOT NULL
  ,multiplayer                       INTEGER  NOT NULL
  ,multiple_endings                  INTEGER  NOT NULL
  ,music                             INTEGER  NOT NULL
  ,music_based_procedural_generation INTEGER  NOT NULL
  ,mystery                           INTEGER  NOT NULL
  ,mystery_dungeon                   INTEGER  NOT NULL
  ,mythology                         INTEGER  NOT NULL
  ,nsfw                              INTEGER  NOT NULL
  ,narration                         INTEGER  NOT NULL
  ,naval                             INTEGER  NOT NULL
  ,ninja                             INTEGER  NOT NULL
  ,noir                              INTEGER  NOT NULL
  ,nonlinear                         INTEGER  NOT NULL
  ,nudity                            INTEGER  NOT NULL
  ,offroad                           INTEGER  NOT NULL
  ,old_school                        INTEGER  NOT NULL
  ,on_rails_shooter                  INTEGER  NOT NULL
  ,online_co_op                      INTEGER  NOT NULL
  ,open_world                        INTEGER  NOT NULL
  ,otome                             INTEGER  NOT NULL
  ,parkour                           INTEGER  NOT NULL
  ,parody_                           INTEGER  NOT NULL
  ,party_based_rpg                   INTEGER  NOT NULL
  ,perma_death                       INTEGER  NOT NULL
  ,philisophical                     INTEGER  NOT NULL
  ,photo_editing                     INTEGER  NOT NULL
  ,physics                           INTEGER  NOT NULL
  ,pinball                           INTEGER  NOT NULL
  ,pirates                           INTEGER  NOT NULL
  ,pixel_graphics                    INTEGER  NOT NULL
  ,platformer                        INTEGER  NOT NULL
  ,point_click                       INTEGER  NOT NULL
  ,political                         INTEGER  NOT NULL
  ,politics                          INTEGER  NOT NULL
  ,pool                              INTEGER  NOT NULL
  ,post_apocalyptic                  INTEGER  NOT NULL
  ,procedural_generation             INTEGER  NOT NULL
  ,programming                       INTEGER  NOT NULL
  ,psychedelic                       INTEGER  NOT NULL
  ,psychological                     INTEGER  NOT NULL
  ,psychological_horror              INTEGER  NOT NULL
  ,puzzle                            INTEGER  NOT NULL
  ,puzzle_platformer                 INTEGER  NOT NULL
  ,pve                               INTEGER  NOT NULL
  ,pvp                               INTEGER  NOT NULL
  ,quick_time_events                 INTEGER  NOT NULL
  ,rpg                               INTEGER  NOT NULL
  ,rpgmaker                          INTEGER  NOT NULL
  ,rts                               INTEGER  NOT NULL
  ,racing                            INTEGER  NOT NULL
  ,real_time_tactics                 INTEGER  NOT NULL
  ,real_time                         INTEGER  NOT NULL
  ,real_time_with_pause              INTEGER  NOT NULL
  ,realistic                         INTEGER  NOT NULL
  ,relaxing                          INTEGER  NOT NULL
  ,remake                            INTEGER  NOT NULL
  ,replay_value                      INTEGER  NOT NULL
  ,resource_management               INTEGER  NOT NULL
  ,retro                             INTEGER  NOT NULL
  ,rhythm                            INTEGER  NOT NULL
  ,robots                            INTEGER  NOT NULL
  ,rogue_like                        INTEGER  NOT NULL
  ,rogue_lite                        INTEGER  NOT NULL
  ,romance                           INTEGER  NOT NULL
  ,rome                              INTEGER  NOT NULL
  ,runner                            INTEGER  NOT NULL
  ,sailing                           INTEGER  NOT NULL
  ,sandbox                           INTEGER  NOT NULL
  ,satire                            INTEGER  NOT NULL
  ,sci_fi                            INTEGER  NOT NULL
  ,science                           INTEGER  NOT NULL
  ,score_attack                      INTEGER  NOT NULL
  ,sequel                            INTEGER  NOT NULL
  ,sexual_content                    INTEGER  NOT NULL
  ,shoot_em_up                       INTEGER  NOT NULL
  ,shooter                           INTEGER  NOT NULL
  ,short                             INTEGER  NOT NULL
  ,side_scroller                     INTEGER  NOT NULL
  ,silent_protagonist                INTEGER  NOT NULL
  ,simulation                        INTEGER  NOT NULL
  ,singleplayer                      INTEGER  NOT NULL
  ,skateboarding                     INTEGER  NOT NULL
  ,skating                           INTEGER  NOT NULL
  ,skiing                            INTEGER  NOT NULL
  ,sniper                            INTEGER  NOT NULL
  ,snow                              INTEGER  NOT NULL
  ,snowboarding                      INTEGER  NOT NULL
  ,soccer                            INTEGER  NOT NULL
  ,software                          INTEGER  NOT NULL
  ,software_training                 INTEGER  NOT NULL
  ,sokoban                           INTEGER  NOT NULL
  ,souls_like                        INTEGER  NOT NULL
  ,soundtrack                        INTEGER  NOT NULL
  ,space                             INTEGER  NOT NULL
  ,space_sim                         INTEGER  NOT NULL
  ,spectacle_fighter                 INTEGER  NOT NULL
  ,spelling                          INTEGER  NOT NULL
  ,split_screen                      INTEGER  NOT NULL
  ,sports                            INTEGER  NOT NULL
  ,star_wars                         INTEGER  NOT NULL
  ,stealth                           INTEGER  NOT NULL
  ,steam_machine                     INTEGER  NOT NULL
  ,steampunk                         INTEGER  NOT NULL
  ,story_rich                        INTEGER  NOT NULL
  ,strategy                          INTEGER  NOT NULL
  ,strategy_rpg                      INTEGER  NOT NULL
  ,stylized                          INTEGER  NOT NULL
  ,submarine                         INTEGER  NOT NULL
  ,superhero                         INTEGER  NOT NULL
  ,supernatural                      INTEGER  NOT NULL
  ,surreal                           INTEGER  NOT NULL
  ,survival                          INTEGER  NOT NULL
  ,survival_horror                   INTEGER  NOT NULL
  ,swordplay                         INTEGER  NOT NULL
  ,tactical                          INTEGER  NOT NULL
  ,tactical_rpg                      INTEGER  NOT NULL
  ,tanks                             INTEGER  NOT NULL
  ,team_based                        INTEGER  NOT NULL
  ,tennis                            INTEGER  NOT NULL
  ,text_based                        INTEGER  NOT NULL
  ,third_person                      INTEGER  NOT NULL
  ,third_person_shooter              INTEGER  NOT NULL
  ,thriller                          INTEGER  NOT NULL
  ,time_attack                       INTEGER  NOT NULL
  ,time_management                   INTEGER  NOT NULL
  ,time_manipulation                 INTEGER  NOT NULL
  ,time_travel                       INTEGER  NOT NULL
  ,top_down                          INTEGER  NOT NULL
  ,top_down_shooter                  INTEGER  NOT NULL
  ,touch_friendly                    INTEGER  NOT NULL
  ,tower_defense                     INTEGER  NOT NULL
  ,trackir                           INTEGER  NOT NULL
  ,trading                           INTEGER  NOT NULL
  ,trading_card_game                 INTEGER  NOT NULL
  ,trains                            INTEGER  NOT NULL
  ,transhumanism                     INTEGER  NOT NULL
  ,turn_based                        INTEGER  NOT NULL
  ,turn_based_combat                 INTEGER  NOT NULL
  ,turn_based_strategy               INTEGER  NOT NULL
  ,turn_based_tactics                INTEGER  NOT NULL
  ,tutorial                          INTEGER  NOT NULL
  ,twin_stick_shooter                INTEGER  NOT NULL
  ,typing                            INTEGER  NOT NULL
  ,underground                       INTEGER  NOT NULL
  ,underwater                        INTEGER  NOT NULL
  ,unforgiving                       INTEGER  NOT NULL
  ,utilities                         INTEGER  NOT NULL
  ,vr                                INTEGER  NOT NULL
  ,vr_only                           BIT  NOT NULL
  ,vampire                           INTEGER  NOT NULL
  ,video_production                  INTEGER  NOT NULL
  ,villain_protagonist               INTEGER  NOT NULL
  ,violent                           INTEGER  NOT NULL
  ,visual_novel                      INTEGER  NOT NULL
  ,voice_control                     INTEGER  NOT NULL
  ,voxel                             INTEGER  NOT NULL
  ,walking_simulator                 INTEGER  NOT NULL
  ,war                               INTEGER  NOT NULL
  ,wargame                           INTEGER  NOT NULL
  ,warhammer_40k                     INTEGER  NOT NULL
  ,web_publishing                    INTEGER  NOT NULL
  ,werewolves                        INTEGER  NOT NULL
  ,western                           INTEGER  NOT NULL
  ,word_game                         INTEGER  NOT NULL
  ,world_war_i                       INTEGER  NOT NULL
  ,world_war_ii                      INTEGER  NOT NULL
  ,wrestling                         INTEGER  NOT NULL
  ,zombies                           INTEGER  NOT NULL
  ,e_sports                          INTEGER  NOT NULL
);

ALTER TABLE `game_reqs` ADD FOREIGN KEY (`steam_appid`) REFERENCES `game` (`appid`);

ALTER TABLE `game_support` ADD FOREIGN KEY (`steam_appid`) REFERENCES `game` (`appid`);

ALTER TABLE `game_tags` ADD FOREIGN KEY (`appid`) REFERENCES `game` (`appid`);

SELECT * FROM game_reqs WHERE steam_appid IS NOT NULL;